lab:
  Stereo:
    red:
      min: [40, 138, 118]
      max: [180, 170, 132]
    pink:
      min: [40, 138, 118]
      max: [180, 170, 132]
    green:
      min: [20, 0, 0]
      max: [255, 120, 170]
    blue:
      min: [20, 145, 20]
      max: [220, 200, 125]
    yellow:
      min: [60, 118, 145]
      max: [220, 145, 190]
    orange:
      min: [50, 135, 145]
      max: [255, 190, 255]
    white:
      min: [175, 0, 0]
      max: [255, 145, 145]
    black:
      min: [0, 0, 0]
      max: [90, 255, 255]
